### ISSUE TITLE
specify a page/resultsPerPage in the CLI

### ISSUE THREAD

**Issue by huglester** [serp-spider/serps-cli#1]
Hello,

I tried searching the source, etc, for a way to specify how much results I would like to search for example first 20pages.

How would I specify offset or page number?

thank you

**Comment by gsouf** [comment]
Hi @huglester 

You have two solutions:

You can make 1 query per page, incrementing the page number with `setPage`: http://serp-spider.github.io/documentation/search-engine/google/google-url/#setpage

Or make 1 query with more results per page with `setResultPerPage`: http://serp-spider.github.io/documentation/search-engine/google/google-url/#setresultsperpage

In your case the second solution will require at least 2 request bcause parsing 20 pages involves 200 results, and google allows at most 100 results per page.

I'm closing the issue, feel free to open it again if you still have a problem with setting the page number.

**Comment by huglester** [comment]
But how this is achieved via CLI?
serps google search --tld="com" --lr="lang_en" --setResultPerPage=100 "github"
there is no such option. maybe providing settings is done another way?

btw I can't reopen I thinK! :)

**Comment by gsouf** [comment]
Ho, glad to see you are using the cli tool. Unfortunately, there is currently no option to provide a result per page or page number from the cli options. That might be an useful addition. I'm opening a dedicated issue for that.

Please know that the cli tool is not very mature yet. At the current stage it was mostly done for fast debugging and the way it works might slightly change in the future.

Edit: my fault, you already created the issue in the cli repository, I'm very absent minded sometimes!

**Comment by huglester** [comment]
but how do you see it? how you will want to pass these params? When you think you will have time to look into this 'feature'? 

"Edit: my fault, you already created the issue in the cli repository, I'm very absent minded sometimes" - not at all! :)

**Comment by gsouf** [comment]
I can see 2 obvious ways:

one way by providing the parameter as a cli argument:

```
serps google search --page=2 --results-per-page=100 "some keywords"
```

Or allowing to give an url for searching:

```
serps google parse-url "google.com/search?q=some+keywords&num=100&start=100"
```

**Comment by huglester** [comment]
first option is like it should be

and 2nd one will give all the flexibility :)

**Comment by gsouf** [comment]
--page and --res-per-page are now available

**Comment by huglester** [comment]
Thank you!
