### ISSUE TITLE
GetOptionKit\Exception\OptionConflictException: Option conflict: -c is already defined.

### ISSUE THREAD

**Issue by stremshs** [serp-spider/serps-cli#2]
Hi guys, 
Congrats for your work. Unfortunately I can't get it to work. 
When cloning from github, and updating every project with _composer update_, i get this error when launching _serps/serps-cli/bin/serps_ help :+1: 

> GetOptionKit\Exception\OptionConflictException: Option conflict: -c is already defined.

`Trace:

    0) GetOptionKit\OptionCollection->addOption(* key:compress spec:-c, --compress[=]  desc:compress type: gz, bz2
  value =>
)
    1) GetOptionKit\OptionCollection->add('c|compress?', 'compress type: gz, bz2')
    2) CLIFramework\Command\ArchiveCommand->options(GetOptionKit\OptionCollection)
    3) CLIFramework\CommandBase->_init()
    4) CLIFramework\CommandBase->createCommand('CLIFramework\\Command\\ArchiveCommand')
    5) CLIFramework\CommandBase->addCommand('archive', 'CLIFramework\\Command\\ArchiveCommand')
    6) CLIFramework\CommandBase->addCommandGroup('Development Commands', [zsh => 'CLIFramework\\Command\\ZshCompletionCommand'bash => 'CLIFramework\\Command\\BashCompletionCommand'meta => 'CLIFramework\\Command\\MetaCommand'compile => 'CLIFramework\\Command\\CompileCommand'archive => 'CLIFramework\\Command\\ArchiveCommand'github:build-topics => 'CLIFramework\\Command\\BuildGitHubWikiTopicsCommand'])
    7) CLIFramework\CommandBase->commandGroup('Development Commands', [zsh => 'CLIFramework\\Command\\ZshCompletionCommand'bash => 'CLIFramework\\Command\\BashCompletionCommand'meta => 'CLIFramework\\Command\\MetaCommand'compile => 'CLIFramework\\Command\\CompileCommand'archive => 'CLIFramework\\Command\\ArchiveCommand'github:build-topics => 'CLIFramework\\Command\\BuildGitHubWikiTopicsCommand'])
    8) CLIFramework\Application->init()
    9) SerpsCli\Console->init()
    10) CLIFramework\CommandBase->_init()
    11) CLIFramework\Application->run(['./serps', 'help'])
    12) CLIFramework\Application->runWithTry(['./serps', 'help'])`

I'm on an Amazon Linux AMI (EC2) which seems to be RHEL FEDORA alike.

Any clue ?

Cheers,

**Comment by gsouf** [comment]
Hi @stremshs 

Yes I noticed the issue too. I think it's an update from the cli framework used behind.
I need to investigate and I think I'm going to use symfony console component instead.

Stay tunned and thanks for reporting

**Comment by gsouf** [comment]
Hi @stremshs 

The issue was fixed in 8996d7fbb8847985081d4d5e118d28747a014055 by using symfony/console instead
