### ISSUE TITLE
serps cli installation fail

### ISSUE THREAD

**Issue by madouz** [serp-spider/serps-cli#4]
Hi. I have run composer require to install serps cli on kali linux but it does not install. It creates zipped files instead in composer cache directory. How do i install this?

**Comment by gsouf** [comment]
Hi @madouz 

Did you run `composer global require serps/cli`?

**Comment by madouz** [comment]
Yes did exactly that. Running this command creates 5 folders in /root/.cache/composer/files/serps namely cli, core, http-client-curl, http-client-phantomjs, saerch-engine-google and within each folder there is only a zipped file for example in cli folder there is c9580003adcf6df8c628059832cea39c2f431829.zip file. Don't have a clue why?

**Comment by gsouf** [comment]
@madouz that's normal. You dont have to deal with that cache directory.

Instead it should have installed in `~/.composer` in which you have a directory named `bin` that must be in your env variable `PATH`. I'm not sure what the right way to do with kali, but it's most likely should be in your `.bashrc` file

**Comment by madouz** [comment]
I have Composer version 1.2.2 installed but there is no /.composer directory.

**Comment by gsouf** [comment]
@madouz that should be in your home directory. If you cannot find it here, I'm affraid I cannot help more because it could be specific to kali linux. 

Maybe this can help: https://stackoverflow.com/questions/30664220/where-to-find-composers-global-packages

**Comment by madouz** [comment]
Problem solved. Needed to create .composer directory and reconfigure home. Strange why kali doesnt create it. Thanks.

**Comment by gsouf** [comment]
Glad It's fixed
